include(ExternalProject)

ExternalProject_Add(LibLZMA
  GIT_REPOSITORY    https://git.avmenergo.ru/avm-energo/xz-utils.git
  GIT_TAG           master
  PREFIX 3rd_party
  CMAKE_ARGS
    -DBUILD_SHARED_LIBS=ON
    -DXZ_TOOL_XZDEC=OFF
    -DXZ_TOOL_LZMADEC=ON
    -DXZ_TOOL_LZMAINFO=OFF
    -DXZ_TOOL_XZ=OFF
    -DXZ_TOOL_SCRIPTS=OFF
    -DXZ_DOXYGEN=OFF
    -DXZ_DOC=OFF
    -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}
    -DCMAKE_INSTALL_LIBDIR=${CMAKE_CURRENT_BINARY_DIR}/lib
    -DCMAKE_INSTALL_INCLUDEDIR=${CMAKE_CURRENT_BINARY_DIR}/include
    -DCMAKE_BUILD_TYPE=${CMAKE_BUILD_TYPE}

  #CONFIGURE_COMMAND ""
  #BUILD_COMMAND ""
  #INSTALL_COMMAND ""
  #BUILD_BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/lib"
)

SET(LibLZMA_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR}/include)
SET(LibLZMA_LIB_DIR ${CMAKE_CURRENT_BINARY_DIR}/lib)
SET(LibLZMA_BIN_DIR ${CMAKE_CURRENT_BINARY_DIR}/bin)

set_target_properties(LibLZMA PROPERTIES
    IMPORTED_LOCATION_DEBUG ${LibLZMA_BIN_DIR}/liblzma${CMAKE_SHARED_LIBRARY_SUFFIX}
    IMPORTED_IMPLIB_DEBUG ${LibLZMA_BIN_DIR}
    IMPORTED_LOCATION_RELEASE ${LibLZMA_BIN_DIR}/liblzma${CMAKE_SHARED_LIBRARY_SUFFIX}
    IMPORTED_IMPLIB_RELEASE ${LibLZMA_BIN_DIR})
